#
# developブランチへのPRがマージされたとき、developブランチのバージョン番号を上げる
# Run `npm version patch` when a PR is merged onto the develop branch.
#
name: patch version up

on:
  pull_request:
    branches:
      - develop
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          token: ${{ secrets.G_ACTIONS_TOKEN_FOR_PR  }}
          
      - name: git setup
        run: |
          git config --global user.email "no-reply@digital.go.jp"
          git config --global user.name "github actions"
          
      - name: bump up (on develop)
        run: |
          npm version patch
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.G_ACTIONS_TOKEN_FOR_PR }}
