## This workflow has been disabled for now, because the CKAN API is blocking our requests.
## Re-enable when we can package test data inside this repository.

name: "PR check"

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    # Set up concurrency so the SQLite cache can be reused between nodejs matrix versions
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # - uses: actions/cache@v3
      #   name: Setup npm cache
      #   id: node_modules
      #   with:
      #     path: node_modules/
      #     key: ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}
      #     restore-keys: |
      #       ${{ runner.os }}-npm-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        # if: steps.node_modules.outputs.cache-hit != 'true'
        run: npm install

      - name: Run eslint on changed files
        uses: sibiraj-s/action-eslint@v3
        with:
          extensions: 'ts'
          ignore-path: .eslintignore
          ignore-patterns: |
            build/
            node_modules/
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: build test
        shell: bash
        run: |
          npm run build
      
      - name: Run tests
        run: |
          npx jest --coverage | tee ./coverage.txt && exit ${PIPESTATUS[0]}

      - name: create test report
        uses: MishaKav/jest-coverage-comment@main
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          coverage-path: ./coverage.txt
  