## This workflow has been disabled for now, because the CKAN API is blocking our requests.
## Re-enable when we can package test data inside this repository.

name: "PR check"

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    # Set up concurrency so the SQLite cache can be reused between nodejs matrix versions
    # concurrency:
    #   group: ${{ github.workflow }}-${{ github.ref }}

    steps:
      - uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        id: node_modules
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        if: steps.node_modules.outputs.cache-hit != 'true'
        run: pnpm install

      - name: Run eslint on changed files
        uses: sibiraj-s/action-eslint@v3
        with:
          extensions: 'ts'
          ignore-path: .eslintignore
          ignore-patterns: |
            build/
            node_modules/

      - name: build test
        shell: bash
        run: |
          pnpm run build
      
      - name: create test report
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: pnpm
          skip-step: install
  